name: test-deploy 

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: thesearenotpineapples95/amneziawg-go-with-api:dev

      - name: Run docker-compose
        run: make run

      - name: Clean up old containers
        run: docker system prune -f --volumes

