name: test-deploy 

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in a DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Clean up old containers
        run: docker system prune -f --volumes

