name: test-deploy 

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run test script
        run:
         bash ~/test_deploy/deploy.sh

